# js中的错误处理


## 1. try-catch

try-catch是错误处理中经常使用的一种方式，但是他只能处理同步代码，是无法捕捉异步代码

- 处理同步代码举例（正确事例）
```javascript
function add(a,b){
  return a*b
}
try {
  add(1)

}catch(e){
  console.log('e',e)
  // 这里会捕获到：  e  ReferenceError: c is not defined
}
```

- 试图捕获异步代码举例（错误事例）
```javascript
function handleAsyncThing(){
  setTimeout(()=>{
    throw Error('你抓不到我，哈哈哈')
  },0)
}

try{
  handleAsyncThing()
}catch(e){
  console.log('e',e)
  //不会执行这里的逻辑， 在浏览器环境中会报： ‘Uncaught Error: 你抓不到我，哈哈哈’
}
```


## error-first（错误优先） 错误处理风格

- 在上面代码，将test中的回调函数的第一个参数设置为错误信息，如果有错误就处理，没有错误就把第一个位置的参数设置为null
- 如果留意的话，这在很多库里都是这么实现的

```javascript

function test(cb){
  setTimeout(()=>{
    try{
      const res=(function(a,b){
        return a+b+c
      })(1,2)
      console.log('try')

      cb(null,res)

    }catch(e){
      console.log('e',e)
      cb(e)
    }
  },0)
}


test((err,res)=>{
  if(err){
    console.log('err',err)
  }else {
    console.log('res',res)
  }
})

```

